[package]
name = "dfs-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ring = "0.17.8"
sha2 = "0.10.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tokio = { version = "1.40.0", features = ["full"] }
clap = { version = "4.5.20", features = ["derive"] }
