
[package]
name = "dfs-client"
version = "0.1.0"
edition = "2021"

[dependencies]
ring = "0.17.8"
sha2 = "0.10.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tokio = { version = "1.40.0", features = ["full"] }
axum = { version = "0.7.9", features = ["ws"] }
# clap = { version = "4.5.20", features = ["derive"] }
hex = "0.4"
serde_json = "1.0.134"
native-dialog = "0.7.0"
tonic = "0.12.3"
futures = "0.3"            # Add futures for StreamExt and SinkExt
tokio-stream = "0.1"       # Add tokio-stream for working with streams in a tokio context
tokio-tungstenite = "0.15" # Add tokio-tungstenite for WebSocket support
hyper = "0.14"

[build-dependencies]
tonic-build = "0.9"
